articles:
    show_translation: true
correctness_match_mode: exact_match
current_language: english
languages:
    - english
    - japanese
next_one_order: random
phrases:
    next_one_order: ""
    show_translation: true
sentences:
    next_one_order: ""
    show_translation: true
words:
    next_one_order: ""
    show_translation: true
