articles: {}
correctness_match_mode: word_match
current_language: english
input_keyboard_sound: true
languages:
    - english
    - japanese
next_one_order: ebbinghaus
phrases: {}
sentences: {}
show_translation: false
words: {}
